### ISSUE TITLE
Cannot read property 'current' of undefined

### ISSUE THREAD

**Issue by dodg3r** [LordMike/MBW.BlueRiiot2MQTT#51]
Hi

Any idea why this shows in logs?
Everything worked fine until today.

```
[14:40:54 INF] Loading extra config file at /data/options.json
[2021-05-29 14:40:54+00:00 INF] [MqttNet.ManagedMqttClient] Started
[2021-05-29 14:40:54+00:00 INF] [MqttNet.MqttClient] Connected.
[2021-05-29 14:40:54+00:00 INF] [Microsoft.Hosting.Lifetime] Application started. Press Ctrl+C to shut down.
[2021-05-29 14:40:54+00:00 INF] [Microsoft.Hosting.Lifetime] Hosting environment: Production
[2021-05-29 14:40:54+00:00 INF] [Microsoft.Hosting.Lifetime] Content root path: /app
[2021-05-29 14:40:55+00:00 INF] [MBW.BlueRiiot2MQTT.Service.BlueRiiotMqttService] Discovered new pool, 'HiBerry Pool' (1c47f0a1-89ad-4ee9-89c4-f20cc7fbd606)
[2021-05-29 14:40:58+00:00 ERR] [MBW.BlueRiiot2MQTT.Service.PoolUpdater.SingleBlueRiiotPoolUpdater] An error occurred while performing the update for pool 1c47f0a1-89ad-4ee9-89c4-f20cc7fbd606
System.Exception: API responded with an error: Cannot read property 'current' of undefined. Path: 'swimming_pool/1c47f0a1-89ad-4ee9-89c4-f20cc7fbd606/weather?lang=en'.
at MBW.Client.BlueRiiotApi.BlueClient.PerformHttp[TRequest,TResponse](String path, HttpMethod method, TRequest requestBody, CancellationToken token) at MBW.Client.BlueRiiotApi.BlueClient.GetSwimmingPoolWeather(String poolId, String lang, CancellationToken token) at MBW.BlueRiiot2MQTT.Service.PoolUpdater.SingleBlueRiiotPoolUpdater.PerformUpdate(CancellationToken stoppingToken) in /src/MBW.BlueRiiot2MQTT/Service/PoolUpdater/SingleBlueRiiotPoolUpdater.cs:line 220
at MBW.BlueRiiot2MQTT.Service.PoolUpdater.SingleBlueRiiotPoolUpdater.Run() in /src/MBW.BlueRiiot2MQTT/Service/PoolUpdater/SingleBlueRiiotPoolUpdater.cs:line 83
[2021-05-29 14:40:58+00:00 INF] [MBW.BlueRiiot2MQTT.Service.PoolUpdater.SingleBlueRiiotPoolUpdater] Delaying till next check on pool 'HiBerry Pool', at 05/29/2021 22:40:58, waiting 08:00:09.9986464
[2021-05-29 14:40:58+00:00 INF] [MBW.HassMQTT.HassMqttManager] Pushed 17 discovery documents, 16 values and 17 attribute changes
```

**Comment by dodg3r** [comment]
Update:

My blue connect app can not load wheater forecast for some reason. 
Could it be that issue thats crashing the integration?

**Comment by kiekerjan18** [comment]
same issue

**Comment by ggggh** [comment]
Same, and as mentioned in #48 is also causing ReportUnchangedValues to not work as expected.
This property (weather) was failing earlier in the week, then got fixed, and now is failing again.  This is also failing on the app, so is not a problem in blueriiot2mqtt.

**Comment by dodg3r** [comment]
Yes. Same as #48. I'm closing this then.
