### ISSUE TITLE
Change Server

### ISSUE THREAD

**Issue by Homeelec** [LordMike/MBW.BlueRiiot2MQTT#53]
Hello,
I am a french user.
In France we have a version from Irrijardin "Joey"
https://joey.irripool.fr/?gclid=CjwKCAjwqvyFBhB7EiwAER786dQQPRhUrK36O8BPXm6jOy4rs4qGmYr1S8zIwTxJORfANCuhMoobhxoCDagQAvD_BwE
I think they are the same products.
I tried to connect my analyzer to the Blueriiot application without success.
I tried to use your add-on without success too.
It seems to me that the servers are not the same.
BlueRiiot server: https://api.riiotlabs.com/prod/
Joey server: https://irrilake-ws.cloud.irripool.net/
My question is: How can I change the server to be connected?

thanks for your help

**Comment by LordMike** [comment]
Uhm, you can't right now. But damn, uhm, lemme expose a parameter for the servers URL.

Be aware that I will likely be completely unable to troubleshoot anything for this.

**Comment by LordMike** [comment]
Try the `:dev` tag, @Homeelec. With it, you should be able to set the environment variable `BlueRiiot__ServerUrl` to your french server, and see if it works.

The docker image should arrive momentarily.

**Comment by Homeelec** [comment]
thank you for the answer I will try

**Comment by Homeelec** [comment]
It doesn't work

My config in HA:

MQTT:
  Server: @.@.@.@
  Port: 1883
  Username: ''
  Password: ''
  ClientId: blueriiot2mqtt
BlueRiiot:
  Username: @@@@@@gmail.com
  Password: @@@@@@@@@@@@
  Language: en
  DiscoveryInterval: '12:00:00'
  UpdateInterval: '01:00:00'
  UpdateIntervalWhenAllDevicesAsleep: '08:00:00'
  ReportUnchangedValues: true
  ServerUrl: irrilake-ws.cloud.irripool.net
HASS:
  DiscoveryPrefix: homeassistant
  TopicPrefix: blueriiot
  EnableHASSDiscovery: true


Debug in HA:

[07:50:01 INF] Loading extra config file at /data/options.json
[2021-06-09 07:50:03+00:00 INF] [MqttNet.ManagedMqttClient] Started
[2021-06-09 07:50:03+00:00 INF] [MqttNet.MqttClient] Connected.
[2021-06-09 07:50:04+00:00 INF] [Microsoft.Hosting.Lifetime] Application started. Press Ctrl+C to shut down.
[2021-06-09 07:50:04+00:00 INF] [Microsoft.Hosting.Lifetime] Hosting environment: Production
[2021-06-09 07:50:04+00:00 INF] [Microsoft.Hosting.Lifetime] Content root path: /app
[2021-06-09 07:50:06+00:00 ERR] [MBW.BlueRiiot2MQTT.Service.BlueRiiotMqttService] An error occurred while performing the update
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at MBW.Client.BlueRiiotApi.BlueClient.LoginWithUsernamePassword(String email, String password, CancellationToken token)
   at MBW.Client.BlueRiiotApi.Builder.UsernamePasswordRequestSigner.LoginIfNeeded(BlueClient client, CancellationToken token)
   at MBW.Client.BlueRiiotApi.BlueClient.PerformHttp[TRequest,TResponse](String path, HttpMethod method, TRequest requestBody, CancellationToken token)
   at MBW.Client.BlueRiiotApi.BlueClient.GetSwimmingPools(Boolean deleted, CancellationToken token)
   at MBW.BlueRiiot2MQTT.Service.BlueRiiotMqttService.PerformUpdate(CancellationToken stoppingToken) in /src/MBW.BlueRiiot2MQTT/Service/BlueRiiotMqttService.cs:line 130
   at MBW.BlueRiiot2MQTT.Service.BlueRiiotMqttService.ExecuteAsync(CancellationToken stoppingToken) in /src/MBW.BlueRiiot2MQTT/Service/BlueRiiotMqttService.cs:line 72

**Comment by LordMike** [comment]
You can enable more logging using these two environment variables:

```
Logging__MinimumLevel__Default: Verbose
Logging__MinimumLevel__Override__MBW.Client.BlueRiiotApi: Verbose
```

But assuming your credentials are correct, it could seem they have a different api / different requirements.

**Comment by LordMike** [comment]
Oh wait - your config is the HASS addon. You cannot configure the server url in the HASS addon, that setting isn't exposed there. 

Can you run it in docker standalone?

**Comment by Homeelec** [comment]
Now I run it in docker on Synology
<img width="653" alt="Capture d’écran 2021-06-09 à 12 09 27" src="https://user-images.githubusercontent.com/42802500/121336921-44794e80-c91c-11eb-8845-2dba94cf6a2f.png">

**Comment by Homeelec** [comment]
A friend gave me access to Blueriiot.
When I test with its codes it works that I put:
BlueRiiot__ServerUrl: https://irrilake-ws.cloud.irripool.net
or
BlueRiiot__ServerUrl: irrilake-ws.cloud.irripool.net

**Comment by LordMike** [comment]
Does this mean it works?

**Comment by Homeelec** [comment]
Yes with BlueRiiot logins, but I have the impression that it does not take the value of the server address.
It still uses "https://api.riiotlabs.com/prod/" the one
Even if I put anything in "BlueRiiot__ServerUrl" as a server it works

**Comment by Homeelec** [comment]
Hello, any news,

**Comment by Homeelec** [comment]
Hello,
For my part I tried to move forward with the charles proxy software, and it gives me this structure.
Is she the same as you?

<img width="1169" alt="Charles Proxy" src="https://user-images.githubusercontent.com/42802500/131536297-73423a10-77f4-4c63-ad00-243719a7aab5.png">

If not can tell me the differences?
I also have more details.

![folder](https://user-images.githubusercontent.com/42802500/131536327-b40f918c-9707-44db-88e8-4ed71ef0ea53.png)

**Comment by LordMike** [comment]
> Yes with BlueRiiot logins, but I have the impression that it does not take the value of the server address.
> It still uses "https://api.riiotlabs.com/prod/" the one
> Even if I put anything in "BlueRiiot__ServerUrl" as a server it works

I tested out changing the `BlueRiiot__ServerUrl` environment variable, and I get errors if it's not the BlueRiiot API endpoint. F.ex., changing it to `https://irrilake-ws.cloud.irripool.net/` gives me HTTP 403's, as I don't have credentials (or the API is different):

```
[2021-09-12 23:27:40+02:00 ERR] [MBW.BlueRiiot2MQTT.Service.BlueRiiotMqttService] An error occurred while performing the update
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at MBW.Client.BlueRiiotApi.BlueClient.LoginWithUsernamePassword(String email, String password, CancellationToken token)
   at MBW.Client.BlueRiiotApi.Builder.UsernamePasswordRequestSigner.LoginIfNeeded(BlueClient client, CancellationToken token)
   at MBW.Client.BlueRiiotApi.BlueClient.PerformHttp[TRequest,TResponse](String path, HttpMethod method, TRequest requestBody, CancellationToken token)
   at MBW.Client.BlueRiiotApi.BlueClient.GetSwimmingPools(Boolean deleted, CancellationToken token)
   at MBW.BlueRiiot2MQTT.Service.BlueRiiotMqttService.PerformUpdate(CancellationToken stoppingToken) in N:\Git\Personal\MBW.BlueRiiot2MQTT\MBW.BlueRiiot2MQTT\Service\BlueRiiotMqttService.cs:line 132
   at MBW.BlueRiiot2MQTT.Service.BlueRiiotMqttService.ExecuteAsync(CancellationToken stoppingToken) in N:\Git\Personal\MBW.BlueRiiot2MQTT\MBW.BlueRiiot2MQTT\Service\BlueRiiotMqttService.cs:line 72
```

So I do believe the variable works.

That being said. The structure you show in Charles is similar, but not the same. F.ex., the API for getting pool measurements, is `/swimming_pool/(id)/lastMeasurements` .. while you have `/pools/(id)/measures/last`..

**Comment by Homeelec** [comment]
Ok
Thank you for answer.
