### ISSUE TITLE
error

### ISSUE THREAD

**Issue by foXaCe** [LordMike/MBW.BlueRiiot2MQTT#6]
hello

`[2020-05-28 04:13:50+00:00 ERR] [MBW.BlueRiiot2MQTT.Service.BlueRiiotMqttService] An error occurred while performing the update`

**Comment by foXaCe** [comment]
since yesterday there is what bug. I no longer have an update

**Comment by barto64** [comment]
Same in here

**Comment by LordMike** [comment]
It could be an issue on Blue Riiots end.. Has it resolved itself (I'm still getting updates) - or is it still down?

**Comment by barto64** [comment]
I am still seeing the same error right now.

[2020-05-28 08:14:40+00:00 ERR] [MBW.BlueRiiot2MQTT.Service.BlueRiiotMqttService] An error occurred while performing the update

**Comment by foXaCe** [comment]
always the bug with me

**Comment by barto64** [comment]
I have just seen it is working now. As @LordMike said, it look like a BlueRiiot problem. Strange though is that the app seemed to be working fine. Nevermind ... it works now.

**Comment by LordMike** [comment]
I would really like more details. There _should_ be more data in the log, than the one line ... if not - I need to change that :)

**Comment by foXaCe** [comment]
always in error for me

An error occurred while performing the update

**Comment by barto64** [comment]
Next time, I will try to enable the "debug" level in the "logger" for the addon (I guess is doable as I do for components or custom_components) and shed more light.

**Comment by foXaCe** [comment]
@barto64 does it work for you?

**Comment by barto64** [comment]
Yes. My last update was an hour ago, which is normal.

**Comment by foXaCe** [comment]
An error occurred while performing the update

for me

**Comment by LordMike** [comment]
@foXaCe could you take a screenshot of the log?

**Comment by LordMike** [comment]
I found a bug that prevented more details from coming through. Will push a fix for that.

**Comment by LordMike** [comment]
I've pushed `0.1.4` to provide more details in log output.

**Comment by foXaCe** [comment]
Can't install lordmike/blueriiot2mqtt-aarch64:v0.1.4 -> 404 Client Error: Not Found ("manifest for lordmike/blueriiot2mqtt-aarch64:v0.1.4 not found: manifest unknown: manifest unknown").

**Comment by foXaCe** [comment]
```
[2020-05-28 20:15:04+00:00 ERR] [MBW.BlueRiiot2MQTT.Service.BlueRiiotMqttService] An error occurred while performing the update
System.NullReferenceException: Object reference not set to an instance of an object.
   at MBW.BlueRiiot2MQTT.Features.Pool.PoolGuidanceFeature.UpdateInternal(SwimmingPool pool, String uniqueId, SwimmingPoolGuidanceGetResponse guidance) in /src/MBW.BlueRiiot2MQTT/Features/Pool/PoolGuidanceFeature.cs:line 38
   at MBW.BlueRiiot2MQTT.Features.FeatureUpdaterBaseTyped`1.UpdateInternal(SwimmingPool pool, String uniqueId, Object obj) in /src/MBW.BlueRiiot2MQTT/Features/FeatureUpdaterBase.cs:line 62
   at MBW.BlueRiiot2MQTT.Features.FeatureUpdaterBase.Update(SwimmingPool pool, Object obj) in /src/MBW.BlueRiiot2MQTT/Features/FeatureUpdaterBase.cs:line 26
   at MBW.BlueRiiot2MQTT.Features.FeatureUpdateManager.Update(SwimmingPool pool, Object obj) in /src/MBW.BlueRiiot2MQTT/Features/FeatureUpdateManager.cs:line 25
   at MBW.BlueRiiot2MQTT.Service.BlueRiiotMqttService.PerformUpdate(CancellationToken stoppingToken) in /src/MBW.BlueRiiot2MQTT/Service/BlueRiiotMqttService.cs:line 114
   at MBW.BlueRiiot2MQTT.Service.BlueRiiotMqttService.ExecuteAsync(CancellationToken stoppingToken) in /src/MBW.BlueRiiot2MQTT/Service/BlueRiiotMqttService.cs:line 60
```

**Comment by LordMike** [comment]
Ok. So you have a guidance that apparently doesn't have an "issue to fix". Hadn't seen this before, so I'll push a `0.2.1` to do _something_..

**Comment by LordMike** [comment]
Also. I think I figured out multiarch images, so I've moved some stuff around.

**Comment by foXaCe** [comment]
ok now it work thank you

**Comment by LordMike** [comment]
@foXaCe - how's the Guidance look like? ... It may be just a ":" right now.

**Comment by foXaCe** [comment]
![image](https://user-images.githubusercontent.com/290678/83236647-21a64d00-a194-11ea-8ba3-e65394124b64.png)

**Comment by LordMike** [comment]
Yea, I figured as much.. What does the app say for that measurement?

If it says nothing, I'll just remove the text in that case.. If it says something, I'll have to figure out where the text comes from, since I'm obviously reading it wrong :P

**Comment by foXaCe** [comment]
in french

Tout va bien !

**Comment by LordMike** [comment]
Very well.
