### ISSUE TITLE
Connection error since last „restart“ of HA

### ISSUE THREAD

**Issue by Quellweg22** [LordMike/MBW.BlueRiiot2MQTT#67]
If restart HA each Night … since the last restart i have no Connection to MQTT mosquitto … Ive changed nothing in configuration … what Happens? I am not an Deep expert … THX in advance ….

[2022-02-28 18:05:10+00:00 INF] [MBW.HassMQTT.HassMqttManager] Pushed 18 discovery documents, 15 values and 16 attribute changes
[2022-02-28 18:05:10+00:00 INF] [MBW.HassMQTT.HassMqttManager] Pushed 10 discovery documents, 15 values and 16 attribute changes
[2022-02-28 18:05:10+00:00 INF] [MBW.BlueRiiot2MQTT.Service.PoolUpdater.SingleBlueRiiotPoolUpdater] New data ready for pool 'Whirlpool' at 02/28/2022 18:48:13 (interval 01:12:00). Waiting 00:44:52.2628651
[2022-02-28 18:05:10+00:00 INF] [MBW.HassMQTT.HassMqttManager] Pushed 9 discovery documents, 9 values and 9 attribute changes
[2022-02-28 18:05:11+00:00 INF] [MBW.BlueRiiot2MQTT.Service.PoolUpdater.SingleBlueRiiotPoolUpdater] New data ready for pool 'Swimspa' at 02/28/2022 18:06:37 (interval 01:12:00). Waiting 00:01:50.9388037
[2022-02-28 18:05:11+00:00 INF] [MBW.HassMQTT.HassMqttManager] Pushed 7 discovery documents, 8 values and 8 attribute changes
[2022-02-28 18:05:17+00:00 ERR] [MqttNet.MqttClient] Error while connecting with server.
MQTTnet.Exceptions.MqttCommunicationException: Host is unreachable [::ffff:192.168.1.8]:1883
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (113): Host is unreachable [::ffff:192.168.1.8]:1883
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.<>c.<ConnectAsync>b__277_0(IAsyncResult iar)
--- End of stack trace from previous location where exception was thrown ---
   at MQTTnet.Implementations.CrossPlatformSocket.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at MQTTnet.Implementations.MqttTcpChannel.ConnectAsync(CancellationToken cancellationToken)
   at MQTTnet.Internal.MqttTaskTimeout.WaitAsync(Func`2 action, TimeSpan timeout, CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ConnectAsync(TimeSpan timeout, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MQTTnet.Adapter.MqttChannelAdapter.WrapException(Exception exception)
   at MQTTnet.Adapter.MqttChannelAdapter.ConnectAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options, CancellationToken cancellationToken)
[2022-02-28 18:05:17+00:00 INF] [MqttNet.MqttClient] Disconnected.

**Comment by LordMike** [comment]
You're restarting Hassio, right?.. Which you then run both the mosquitto and blueriiot2mqtt on, which means they restart as well..

Something didn't start up properly, either restart mosquitto or restart it all again.
