### ISSUE TITLE
Stopped working - A task was canceled

### ISSUE THREAD

**Issue by EricReiche** [LordMike/MBW.BlueRiiot2MQTT#73]
Hi,

thank you for your work on this piece of software.

Unfortunately it stopped working some days ago for me.
I DID do that firmware update mentioned in #72, but I'm not sure if that is correlation or causation.

Here's the log:
```
[2022-08-24 07:21:26+00:00 INF] [MqttNet.ManagedMqttClient] Started
[2022-08-24 07:21:26+00:00 INF] [MqttNet.MqttClient] Connected.
[2022-08-24 07:21:26+00:00 INF] [Microsoft.Hosting.Lifetime] Application started. Press Ctrl+C to shut down.
[2022-08-24 07:21:26+00:00 INF] [Microsoft.Hosting.Lifetime] Hosting environment: Production
[2022-08-24 07:21:26+00:00 INF] [Microsoft.Hosting.Lifetime] Content root path: /app
[2022-08-24 07:23:06+00:00 ERR] [MBW.BlueRiiot2MQTT.Service.BlueRiiotMqttService] An error occurred while performing the update
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at MBW.Client.BlueRiiotApi.BlueClient.LoginWithUsernamePassword(String email, String password, CancellationToken token)
   at MBW.Client.BlueRiiotApi.Builder.UsernamePasswordRequestSigner.LoginIfNeeded(BlueClient client, CancellationToken token)
   at MBW.Client.BlueRiiotApi.BlueClient.PerformHttp[TRequest,TResponse](String path, HttpMethod method, TRequest requestBody, CancellationToken token)
   at MBW.Client.BlueRiiotApi.BlueClient.GetSwimmingPools(Boolean deleted, CancellationToken token)
   at MBW.BlueRiiot2MQTT.Service.BlueRiiotMqttService.PerformUpdate(CancellationToken stoppingToken) in /src/MBW.BlueRiiot2MQTT/Service/BlueRiiotMqttService.cs:line 132
   at MBW.BlueRiiot2MQTT.Service.BlueRiiotMqttService.ExecuteAsync(CancellationToken stoppingToken) in /src/MBW.BlueRiiot2MQTT/Service/BlueRiiotMqttService.cs:line 75
```

How can I help debug this?

Last successful update was 18th of August 18:28 - I can't remember when I did the update.

**Comment by LordMike** [comment]
This is a timeout when trying to hit BlueRiiots API. Try again later / check if you have internet access.

Mike.
________________________________
From: Eric Reiche ***@***.***>
Sent: Wednesday, August 24, 2022 09:28
To: LordMike/MBW.BlueRiiot2MQTT ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [LordMike/MBW.BlueRiiot2MQTT] Stopped working (Issue #73)


Hi,

thank you for your work on this piece of software.

Unfortunately it stopped working some days ago for me.
I DID do that firmware update mentioned in #72<https://github.com/LordMike/MBW.BlueRiiot2MQTT/issues/72>, but I'm not sure if that is correlation or causation.

Here's the log:

[2022-08-24 07:21:26+00:00 INF] [MqttNet.ManagedMqttClient] Started
[2022-08-24 07:21:26+00:00 INF] [MqttNet.MqttClient] Connected.
[2022-08-24 07:21:26+00:00 INF] [Microsoft.Hosting.Lifetime] Application started. Press Ctrl+C to shut down.
[2022-08-24 07:21:26+00:00 INF] [Microsoft.Hosting.Lifetime] Hosting environment: Production
[2022-08-24 07:21:26+00:00 INF] [Microsoft.Hosting.Lifetime] Content root path: /app
[2022-08-24 07:23:06+00:00 ERR] [MBW.BlueRiiot2MQTT.Service.BlueRiiotMqttService] An error occurred while performing the update
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at MBW.Client.BlueRiiotApi.BlueClient.LoginWithUsernamePassword(String email, String password, CancellationToken token)
   at MBW.Client.BlueRiiotApi.Builder.UsernamePasswordRequestSigner.LoginIfNeeded(BlueClient client, CancellationToken token)
   at MBW.Client.BlueRiiotApi.BlueClient.PerformHttp[TRequest,TResponse](String path, HttpMethod method, TRequest requestBody, CancellationToken token)
   at MBW.Client.BlueRiiotApi.BlueClient.GetSwimmingPools(Boolean deleted, CancellationToken token)
   at MBW.BlueRiiot2MQTT.Service.BlueRiiotMqttService.PerformUpdate(CancellationToken stoppingToken) in /src/MBW.BlueRiiot2MQTT/Service/BlueRiiotMqttService.cs:line 132
   at MBW.BlueRiiot2MQTT.Service.BlueRiiotMqttService.ExecuteAsync(CancellationToken stoppingToken) in /src/MBW.BlueRiiot2MQTT/Service/BlueRiiotMqttService.cs:line 75


How can I help debug this?

**Comment by EricReiche** [comment]
Thanks for pointing me in the right direction, it seems something was wrong with the network settings of the container.
